steps:
  # Build Docker images for the frontend and backend
  - name: 'gcr.io/cbd3354-systems/docker'
    args: ['build', '-t', 'gcr.io/cbd3354-systems/frontend-ui:$SHORT_SHA', './frontend']
  - name: 'gcr.io/cbd3354-systems/docker'
    args: ['build', '-t', 'gcr.io/cbd3354-systems/backend-app:$SHORT_SHA', './backend']
options:
  logging: 'CLOUD_LOGGING_ONLY'
serviceAccount: '60932370226-compute@developer.gserviceaccount.com'
