version: '3'
services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - mynetwork
    environment:
      - DB_HOST=postgres
      - DB_NAME=myappdb
      - DB_USER=jerome
      - DB_PASSWORD=Lnx!2024
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: jerome
      POSTGRES_PASSWORD: Lnx!2024
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"

networks:
  mynetwork:
    driver: bridge